image: python:3.10

definitions:
  caches:
    pip: ~/.cache/pip
  steps:
    - step: &run-tests
        name: Run tests
        caches:
          - pip
        script:
          - apt-get update
          - apt-get install -y default-jre-headless
          - python -m pip install --upgrade pip
          - pip install -e ".[tests]"
          - pytest

pipelines:
  pull-requests:
    "**":
      - step:
          <<: *run-tests
          name: Run tests (PR)

  branches:
    main:
      - step:
          <<: *run-tests
          name: Run tests (main)
