PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX smart:    <https://w3id.org/standards/smart/ontologies/core/>
PREFIX ex:      <https://example.org/>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX oa:      <http://www.w3.org/ns/oa#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?depth ?type ?item ?parent ?previous ?next ?annotation ?target ?section ?title ?value
WHERE {
  VALUES ?root { ex:document_1 }

  VALUES ?supertype {
    smart:Clause
    smart:Provision
  }

  ?type rdfs:subClassOf* ?supertype .

  ?item dcterms:isPartOf+ ?root ;
        dcterms:isPartOf ?parent ;
        a ?type .

  ?annotation oa:hasBody ?item ;
              oa:hasTarget ?target .

  OPTIONAL {
    ?target smart:isSuccessorOf ?previousTarget .
    ?previousAnnotation oa:hasBody ?previous ;
                        oa:hasTarget ?previousTarget .
  }

  OPTIONAL {
    ?nextTarget smart:isSuccessorOf ?target .
    ?nextAnnotation oa:hasBody ?next ;
                    oa:hasTarget ?nextTarget .
  }

  OPTIONAL { ?target rdf:value ?value . }
    
  OPTIONAL { ?target dcterms:title ?title . }
    
  OPTIONAL { ?target smart:hasSectionNumber ?section . }

  {
    SELECT ?item (COUNT(DISTINCT ?ancestor) AS ?depth)
    WHERE {
      VALUES ?root { ex:document_1 }

      ?item dcterms:isPartOf+ ?root .
      ?item dcterms:isPartOf+ ?ancestor .
      ?ancestor dcterms:isPartOf* ?root .
    }
    GROUP BY ?item
  }
}
ORDER BY ?depth ?parent ?previous ?item
